### ISSUE TITLE
uniCloud-云函数模板中使用HbuilderX导入插件无响应问题

### ISSUE THREAD

**Issue by MrZhangDaYe** [dcloudio/hbuilderx-extension-docs#15]
uniCloud-云函数模板中使用HbuilderX导入插件后HbuilderX要求选择一个uni-app项目导入该插件，但是项目列表里没有任何项目。
![企业微信截图_16382417038769](https://user-images.githubusercontent.com/86636399/143978791-945387da-35ff-4ce1-91ca-a2a6b74692d4.png)

**Comment by DCloud-Wan** [comment]
请升级HBuilderX版本
