### ISSUE TITLE
cli 生成本地打包资源

### ISSUE THREAD

**Issue by Scorpio-nan** [dcloudio/hbuilderx-extension-docs#36]
```bash
# 生成本地打包App资源
cli publish --platform APP --type appResource --project 项目名称
```

project 项目名称应该传什么参数?

**Comment by qq824810885** [comment]
传项目管理器里打开的项目的名称，如下：<img width="270" alt="image" src="https://user-images.githubusercontent.com/5110246/163093395-f7a4a94e-1cb0-4ffd-8729-eaf631200222.png">
项目名称为:testUniappDebug.
