### ISSUE TITLE
cli pack --config 配置文件

### ISSUE THREAD

**Issue by wendyJing** [dcloudio/hbuilderx-extension-docs#37]
11:08:45.163 检查云端打包状态...
11:08:50.344 检查打包资源...
11:08:50.969 <ul style="margin-left: -30px; margin-top: -30px;"><li>Android公共测试证书仅用于测试体验，存在安全隐患，在部分安全检测平台可能会误报病毒，请勿用于正式发布应用。详情：<a href="https://ask.dcloud.net.cn/article/36522">https://ask.dcloud.net.cn/article/36522</a></li><li>为落实《网络安全法》《消费者权益保护法》的要求，有效治理App强制授权、过度索权、超范围收集个人信息等现象，保障个人信息安全，国内各大应用市场都加强了应用审核，要求应用必须符合相关政策才能上架，当前应用缺少相关配置，<a href="https://uniapp.dcloud.io/app/android-store">查看如何解决</a>。不上架国内应用市场无需处理。</li></ul>

打包方式：
cli pack --config 配置文件
执行到“检查打包资源”的提示信息后，自动断了打包，怎么忽略提示进行打包

**Comment by DCloud-Wan** [comment]
未复现此问题，请尝试升级HBuilderX
