### ISSUE TITLE
cli 发行H5项目报错

### ISSUE THREAD

**Issue by sagit33569** [dcloudio/hbuilderx-extension-docs#40]
![image](https://user-images.githubusercontent.com/43563049/164169827-7af14747-9da3-410f-ae86-ecfcbc0c4ce9.png)
如图所示，按照官网的cli语法执行命令行打包H5项目，提示
A positional parameter cannot be found that accepts argument '--platform'.
这个错误,，期望得到解答

**Comment by doyoung126** [comment]
试试大写的`H5`

**Comment by yi-heng** [comment]
[](https://img-cdn-tc.dcloud.net.cn/uploads/questions/20220420/ed4cd34af8826b2009fa505a61944af1.png)

**Comment by yi-heng** [comment]
![example](https://img-cdn-tc.dcloud.net.cn/uploads/questions/20220420/ed4cd34af8826b2009fa505a61944af1.png)

**Comment by sagit33569** [comment]
> ![example](https://camo.githubusercontent.com/813af11a2c90b5624da137aadca88b4e01ce29306abef605af393b96a41052a3/68747470733a2f2f696d672d63646e2d74632e64636c6f75642e6e65742e636e2f75706c6f6164732f7175657374696f6e732f32303232303432302f65643463643334616638383236623230303966613530356136313934346166312e706e67)

谢谢，这样可以解决问题，我在windows环境下配置的环境变量应该还有问题，所以会报这样的错误
