### ISSUE TITLE
缺少右键打开项目功能

### ISSUE THREAD

**Issue by social-uni** [dcloudio/hbuilderx-extension-docs#43]
![image](https://user-images.githubusercontent.com/14007972/170239747-b8434d7a-861c-4389-a8ed-6b38e8f4fe6b.png)

webstorm可以右键打开项目，hbuilderx不行，建议支持此功能，方便使用

**Comment by DCloud-Wan** [comment]
HBuilderX 菜单【设置】，常用配置，找到配置项 **关联右键菜单**，并勾选
