### ISSUE TITLE
$DATE_TIME的时候少了现实5天

### ISSUE THREAD

**Issue by Sandrey1204** [dcloudio/hbuilderx-extension-docs#45]
<img width="1304" alt="image" src="https://user-images.githubusercontent.com/27037495/172799101-16257f9f-7ee4-46c3-bc22-db52963f0154.png">

今天是9号，但是生成的日期却是4号。 少了5天， 是什么规则生成的呢？ 能不能自定义

**Comment by DCloud-Wan** [comment]
HBuilderX 3.5.3正式版，已修复此问题
