### ISSUE TITLE
HbuilderX 2.6.16版本 生成本地打包资源 配置了开发者工具   一直提示未检测到微信web开发者工具，即使开发App也需要此工具。如已安装，请确认路径配置是否正确（HBuilderX设置-运行配置-微信开发者工具路径），或检查是否微信工具版本过低

### ISSUE THREAD

**Issue by xiangjiayu** [dcloudio/hbuilderx-extension-docs#48]
配置了高版本的微信开发者工具也不行。 
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/16829649/190365413-3064e936-95b6-4838-ac4b-e687c6b1e90d.png">
<img width="1354" alt="image" src="https://user-images.githubusercontent.com/16829649/190365452-c574db98-0253-44ed-833a-ee1ed0ed5476.png">

**Comment by DCloud-Wan** [comment]
无法复现。升级HBuilderX到最新版试试。
