### ISSUE TITLE
现在hbuilderX支持Vue2吗，代码提示工具总是莫名好使，莫名失效，Vue3就很好用

### ISSUE THREAD

**Issue by bestOneOnly** [dcloudio/hbuilderx-extension-docs#50]
不知道怎么传图片，现在激活代码提示工具就把所有提示都显示出来了，第一个就是AbortController
第一个就是右下角代码库没有Vue选项，第二个   右下角下载按钮左边改成Vue无反应，必须改成HTML，且在代码里输入V才能出现
Vue的生命周期钩子，而且是没有说明的
Vue3同样试了，提示的很准确，公司用的是3.6.3版本，Vue2依旧可以正常提示
-----------------
操作了一个步骤。先取消代码助手，然后再激活代码助手，就会出现下次激活代码助手的时候提示所有的方法

**Comment by DCloud-Wan** [comment]
升级HBuilderX试试
