### ISSUE TITLE
所有插件都安装不了，因为没有update目录

### ISSUE THREAD

**Issue by oldTimor** [dcloudio/hbuilderx-extension-docs#51]
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/39369396/204080035-f0496982-7efd-4e9e-9bda-cd4888c4d2e0.png">

**Comment by DCloud-Wan** [comment]
HBuilderX安装问题。请将HBuilderX安装到应用程序目录。即/Applications目录。教程参考：https://hx.dcloud.net.cn/Tutorial/install/macosx
