### ISSUE TITLE
cli 发布 是否支持 自定义

### ISSUE THREAD

**Issue by shanghen** [dcloudio/hbuilderx-extension-docs#54]
在HBuilderX软件中发行有自定义的子菜单
而cli命令行中找不到相关的选项。
应为项目需要根据不同的编译有不同的环境变量。根据uni-app的文档中找到了在package.js配置。
然而cli中没法进行相关打包部署

**Comment by DCloud-Wan** [comment]
暂不支持。如果后续支持，会在HBuilderX更新日志中说明
