### ISSUE TITLE
HBuilderX 多文件字符搜索,整个项目搜索无结果

### ISSUE THREAD

**Issue by shayebushixiaopacai** [dcloudio/hbuilderx-extension-docs#59]
刚更新的HBuilderX 3.7.12alpha版多文件字符搜索,整个项目搜索无结果,只可以搜索当前打开页面的内容

**Comment by dcloud-wandl** [comment]
HBuilderX安装目录，plugins下，看下是否存在ripgrep目录。

如果不存在，请下载ripgrep，然后解压到此目录，解压后的目录名必须是：`ripgrep`。解压后需要重启HBuilderX

[windows ripgrep下载地址](http://download1.dcloud.net.cn/hbuilderx/dailybuild/win32/plugins/contents/ripgrep.1.8.0-2023033117.zip)

[macosx ripgrep下载地址](http://download1.dcloud.net.cn/hbuilderx/dailybuild/macosx/plugins/contents/ripgrep.1.8.0-2023033120.zip)

#### 或者重装HBuilderX
