### ISSUE TITLE
对文件进行验证有3种触发方式

### ISSUE THREAD

**Issue by januwA** [dcloudio/hbuilderx-extension-docs#7]
我正在 https://hx.dcloud.net.cn/validations 看到此文档

1. 通过点击注册的某个菜单触发验证
2. 监听文档修改事件实时验证
3. 监听文档保存事件验证

在文档中只演示了如何使用第一种方法，关于如何监听文档的修改和监听文档的保存事件，能否提供下文档。

谢谢。

**Comment by qq824810885** [comment]
参考这个文档：http://hx.dcloud.net.cn/ExtensionDocs/Api/README?id=ondidchangetextdocument

**Comment by januwA** [comment]
@qq824810885 谢谢
